### PR TITLE
Fix useEffect warning/memory leak

### PR DESCRIPTION
**Pull request by adamyonk**
Fixes the warning: `Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.`

### CODE REVIEW

**Comment by hipstersmoothie** [comment]
It looks like we can stop using our custom storybook API type since I think they now ship them

**Comment by adamyonk** [comment]
I was just trying to get that tracked down. 😁 I'll get that fixed up.

**Comment by adamyonk** [comment]
Screen Shot 2019-10-29 at 5 15 02 PM

**Comment by hipstersmoothie** [comment]
@adamyonk  I think I figured it out. This should also fix another error I see on the console sometimes. 

Thanks for the contribution!

**Comment by hipstersmoothie** [comment]
:rocket: PR was released in v0.1.9 :rocket:

**Pull request merged**
