### PR TITLE
chore: bump to storybook v7

### PR DESCRIPTION
**Pull request by Himself65**
Fixes: https://github.com/hipstersmoothie/storybook-dark-mode/issues/221

### CODE REVIEW

**Comment by hipstersmoothie** [comment]
I'm down to merge this. but will probably only merge once v7 is released

**Comment by Himself65** [comment]
> I'm down to merge this. but will probably only merge once v7 is released

I agree because it does a breaking change, but could you please release a version like `3.0.0.alpha.0` with the tag `@v7` or something in a new branch?

**Comment by hipstersmoothie** [comment]
I can set that up but not til something this weekend probably

**Comment by JReinhold** [comment]
Hey @hipstersmoothie and @Himself65, Storybook v7.0.0 is out! It's only on the `next` tag for now, but it's still targetable with the `^7.0.0` semver range, so you should be able to develop against it with no dependency issues.

If you hit any issues with v7, we've written a migration guide for addon authors [here](https://github.com/storybookjs/storybook/blob/norbert/add-addon-migration-guide/MIGRATION.md?rgh-link-date=2023-03-31T20%3A21%3A47Z#specific-instructions-for-addon-creators) and [here](https://chromatic-ui.notion.site/Addon-migration-for-Storybook-7-002f2f627c1d470298ca94894ab8a040).

You're also free to reach out to us in the #prerelease channel on our [Discord Server](https://discord.gg/storybook) and we'll happily help you out!

cc @ndelangen

**Comment by Himself65** [comment]
Thank you for the prompt response, I will check the migration guide later

**Review by ndelangen — APPROVED** [review]

**Comment by hipstersmoothie** [comment]
:rocket: PR was released in [`v3.0.0`](https://github.com/hipstersmoothie/storybook-dark-mode/releases/tag/v3.0.0) :rocket:

**Pull request merged**
