### PR TITLE
feat: add media query matcher for operating system theme control

### PR DESCRIPTION
**Pull request by Swiftwork**
New feature using `prefers-color-scheme` media query to determine operating systems preferred theme. Both an initial value is read from the preferences and subsequent updates sent from the system will trigger a change in mode.

### CODE REVIEW

**Comment by Swiftwork** [comment]
storybook-dark-mode-query

**Comment by hipstersmoothie** [comment]
That’s pretty fricken sweet! I’ll take a look at this tomorrow! Thanks for
the contribution

**Comment by Swiftwork** [comment]
Hi @hipstersmoothie,

Im guessing you are pretty busy with your every day work, but have you had time to review this pull request? :)

**Comment by hipstersmoothie** [comment]
:rocket: PR was released in v0.2.0 :rocket:

**Pull request merged**
